//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _GHIELECTRONICS_OSH_NETMF_NATIVE_H_
#define _GHIELECTRONICS_OSH_NETMF_NATIVE_H_

#include <TinyCLR_Interop.h>
struct Library_GHIElectronics_OSH_NETMF_Native_GHIElectronics_OSH_NETMF_Native_RLPLite__Procedure
{
    static const int FIELD__address = 1;

    TINYCLR_NATIVE_DECLARE(Invoke_Helper___I4__SZARRAY_R4__SZARRAY_I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Invoke_Helper___I4__SZARRAY_U4__SZARRAY_I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Invoke_Helper___I4__SZARRAY_I4__SZARRAY_I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Invoke_Helper___I4__SZARRAY_U1__SZARRAY_I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Invoke_Helper___I4__SZARRAY_I1__SZARRAY_I4__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_GHIElectronics_OSH_NETMF_Native;

#endif  //_GHIELECTRONICS_OSH_NETMF_NATIVE_H_
