//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "GHIElectronics_OSH_NETMF_Native.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    Library_GHIElectronics_OSH_NETMF_Native_GHIElectronics_OSH_NETMF_Native_RLPLite__Procedure::Invoke_Helper___I4__SZARRAY_R4__SZARRAY_I4__SZARRAY_U1,
    NULL,
    Library_GHIElectronics_OSH_NETMF_Native_GHIElectronics_OSH_NETMF_Native_RLPLite__Procedure::Invoke_Helper___I4__SZARRAY_U4__SZARRAY_I4__SZARRAY_U1,
    NULL,
    Library_GHIElectronics_OSH_NETMF_Native_GHIElectronics_OSH_NETMF_Native_RLPLite__Procedure::Invoke_Helper___I4__SZARRAY_I4__SZARRAY_I4__SZARRAY_U1,
    NULL,
    Library_GHIElectronics_OSH_NETMF_Native_GHIElectronics_OSH_NETMF_Native_RLPLite__Procedure::Invoke_Helper___I4__SZARRAY_U1__SZARRAY_I4__SZARRAY_U1,
    NULL,
    Library_GHIElectronics_OSH_NETMF_Native_GHIElectronics_OSH_NETMF_Native_RLPLite__Procedure::Invoke_Helper___I4__SZARRAY_I1__SZARRAY_I4__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_GHIElectronics_OSH_NETMF_Native =
{
    "GHIElectronics.OSH.NETMF.Native", 
    0x96095A80,
    method_lookup
};
