//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "GHIElectronics_OSH_NETMF_Hardware.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_AnalogIn::Dispose___VOID,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_AnalogIn::Finalize___VOID,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_AnalogIn::_ctor___VOID__GHIElectronicsOSHNETMFHardwareAnalogInPin,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_AnalogIn::SetLinearScale___VOID__I4__I4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_AnalogIn::Read___I4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_LowLevel_AddressSpace::Write___STATIC__VOID__U4__SZARRAY_U1__I4__I4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_LowLevel_AddressSpace::Read___STATIC__VOID__U4__SZARRAY_U1__I4__I4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_LowLevel_Register::_ctor___VOID__U4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_LowLevel_Register::Write___VOID__U4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_LowLevel_Register::Read___U4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_LowLevel_Register::SetBits___VOID__U4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_LowLevel_Register::ClearBits___VOID__U4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_LowLevel_Register::ToggleBits___VOID__U4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_PWM::Dispose___VOID,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_PWM::Finalize___VOID,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_PWM::_ctor___VOID__GHIElectronicsOSHNETMFHardwarePWMPin,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_PWM::Set___VOID__I4__U1,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_PWM::Set___VOID__BOOLEAN,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_PWM::SetPulse___VOID__U4__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_SoftwareI2CBus::NativeI2CWriteRead___STATIC__BOOLEAN__I4__I4__I4__U2__SZARRAY_U1__I4__I4__SZARRAY_U1__I4__I4__BYREF_I4__BYREF_I4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_StorageDev::MountSD___STATIC__VOID,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_StorageDev::MountSD___STATIC__VOID__U4,
    Library_GHIElectronics_OSH_NETMF_Hardware_GHIElectronics_OSH_NETMF_Hardware_StorageDev::UnmountSD___STATIC__VOID,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_GHIElectronics_OSH_NETMF_Hardware =
{
    "GHIElectronics.OSH.NETMF.Hardware", 
    0x0E23395B,
    method_lookup
};

