//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _HAL_H_
#define _HAL_H_

#include <TinyCLR_Interop.h>
struct Library_HAL_GHI_GameO_LowLevel_Display
{
    TINYCLR_NATIVE_DECLARE(Initialize___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(WriteRaw___STATIC__VOID__U2);
    TINYCLR_NATIVE_DECLARE(WriteRaw___STATIC__VOID__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(WriteRaw___STATIC__VOID__SZARRAY_U2__I4__I4);
    TINYCLR_NATIVE_DECLARE(SetRegister___STATIC__VOID__U2);
    TINYCLR_NATIVE_DECLARE(WriteRegister___STATIC__VOID__U2__U2);
    TINYCLR_NATIVE_DECLARE(SetDrawWindow___STATIC__VOID__U2__U2__U2__U2);
    TINYCLR_NATIVE_DECLARE(DrawImage___STATIC__VOID__SZARRAY_U1__U2__U2__U2__U2__U2__U2__U2__U2);
    TINYCLR_NATIVE_DECLARE(DrawImage___STATIC__VOID__SZARRAY_U2__U2__U2__U2__U2__U2__U2__U2__U2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_GHI_GameO_LowLevel;

#endif  //_HAL_H_
