//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "HAL.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_HAL_GHI_GameO_LowLevel_Display::Initialize___STATIC__VOID,
    Library_HAL_GHI_GameO_LowLevel_Display::WriteRaw___STATIC__VOID__U2,
    Library_HAL_GHI_GameO_LowLevel_Display::WriteRaw___STATIC__VOID__SZARRAY_U1__I4__I4,
    Library_HAL_GHI_GameO_LowLevel_Display::WriteRaw___STATIC__VOID__SZARRAY_U2__I4__I4,
    Library_HAL_GHI_GameO_LowLevel_Display::SetRegister___STATIC__VOID__U2,
    Library_HAL_GHI_GameO_LowLevel_Display::WriteRegister___STATIC__VOID__U2__U2,
    Library_HAL_GHI_GameO_LowLevel_Display::SetDrawWindow___STATIC__VOID__U2__U2__U2__U2,
    Library_HAL_GHI_GameO_LowLevel_Display::DrawImage___STATIC__VOID__SZARRAY_U1__U2__U2__U2__U2__U2__U2__U2__U2,
    Library_HAL_GHI_GameO_LowLevel_Display::DrawImage___STATIC__VOID__SZARRAY_U2__U2__U2__U2__U2__U2__U2__U2__U2,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_GHI_GameO_LowLevel =
{
    "GHI.GameO.LowLevel", 
    0x8E44482A,
    method_lookup
};

