//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _LIB_H_
#define _LIB_H_

#include <TinyCLR_Interop.h>
struct Library_Lib_GHI_Utilities_Bitmaps
{
    TINYCLR_NATIVE_DECLARE(NativeConvert___STATIC__VOID__SZARRAY_U1__SZARRAY_U1__GHIUtilitiesBitmapsBitsPerPixel);
    TINYCLR_NATIVE_DECLARE(NativeConvertToFile___STATIC__VOID__SZARRAY_U1__I4__I4__SZARRAY_U1);

    //--//

};

struct Library_Lib_GHI_IO_ControllerAreaNetwork
{
    static const int FIELD_STATIC__instanceList = 0;
    static const int FIELD_STATIC__instanceListLock = 1;
    static const int FIELD_STATIC__emxTimings = 2;
    static const int FIELD_STATIC__g120Timings = 3;
    static const int FIELD_STATIC__g400Timings = 4;

    static const int FIELD__disposed = 1;
    static const int FIELD__enabled = 2;
    static const int FIELD__channel = 3;
    static const int FIELD__receiveBufferSize = 4;
    static const int FIELD__baudRateRegister = 5;
    static const int FIELD__timings = 6;
    static const int FIELD__MessageAvailable = 7;
    static const int FIELD__ErrorReceived = 8;

    TINYCLR_NATIVE_DECLARE(NativeSetExplicitFilters___VOID__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(NativeSetGroupFilters___VOID__SZARRAY_U4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(NativeEnable___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeDisable___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeReset___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeReceiveErrorCount___I4);
    TINYCLR_NATIVE_DECLARE(NativeTransmitErrorCount___I4);
    TINYCLR_NATIVE_DECLARE(NativeReceivedMessageCount___I4);
    TINYCLR_NATIVE_DECLARE(NativeTransmittedMessagesSent___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeTransmissionAllowed___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeReadMessages___I4__SZARRAY_GHIIOControllerAreaNetworkMessage__I4__I4);
    TINYCLR_NATIVE_DECLARE(NativeSendMessages___I4__SZARRAY_GHIIOControllerAreaNetworkMessage__I4__I4);
    TINYCLR_NATIVE_DECLARE(NativeDiscardIncomingMessages___VOID);
    TINYCLR_NATIVE_DECLARE(NativeSourceClock___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(NativeCalculateRegisterValue___STATIC__U4__I4__I4__I4__I4__I4__BOOLEAN);

    //--//

};

struct Library_Lib_GHI_Usb_Device
{
    static const int FIELD__disposed = 1;
    static const int FIELD__id = 2;
    static const int FIELD__interfaceIndex = 3;
    static const int FIELD__type = 4;
    static const int FIELD__vendorId = 5;
    static const int FIELD__productId = 6;
    static const int FIELD__portNumber = 7;
    static const int FIELD__connected = 8;
    static const int FIELD__Disconnected = 9;


    //--//

};

struct Library_Lib_GHI_Processor_Configuration__Display
{
    static const int FIELD_STATIC__width = 5;
    static const int FIELD_STATIC__height = 6;
    static const int FIELD_STATIC__outputEnableIsFixed = 7;
    static const int FIELD_STATIC__outputEnablePolarity = 8;
    static const int FIELD_STATIC__pixelPolarity = 9;
    static const int FIELD_STATIC__pixelClockRateKHz = 10;
    static const int FIELD_STATIC__horizontalSyncPolarity = 11;
    static const int FIELD_STATIC__horizontalSyncPulseWidth = 12;
    static const int FIELD_STATIC__horizontalBackPorch = 13;
    static const int FIELD_STATIC__horizontalFrontPorch = 14;
    static const int FIELD_STATIC__verticalSyncPolarity = 15;
    static const int FIELD_STATIC__verticalSyncPulseWidth = 16;
    static const int FIELD_STATIC__verticalBackPorch = 17;
    static const int FIELD_STATIC__verticalFrontPorch = 18;
    static const int FIELD_STATIC__bootupMessages = 19;
    static const int FIELD_STATIC__rotation = 20;
    static const int FIELD_STATIC__spiConfiguration = 21;
    static const int FIELD_STATIC__controlPin = 22;
    static const int FIELD_STATIC__bpp = 23;
    static const int FIELD_STATIC__type = 24;

    TINYCLR_NATIVE_DECLARE(NativeGetLcdConfiguration___STATIC__VOID__BYREF_BOOLEAN__BYREF_U1__BYREF_U4__BYREF_U4__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U4);
    TINYCLR_NATIVE_DECLARE(NativeSetLcdConfiguration___STATIC__BOOLEAN__BOOLEAN__U1__U4__U4__BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN__U1__U1__U1__U1__U1__U1__U4);
    TINYCLR_NATIVE_DECLARE(NativeSetSpiConfiguration___STATIC__BOOLEAN__I4__I4__I4__I4__BOOLEAN__BOOLEAN__BOOLEAN__I4__I4__I4__I4__I4__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeSetParallelConfiguration___STATIC__BOOLEAN__I4__I4);

    //--//

};

struct Library_Lib_GHI_IO_ControllerAreaNetwork__ErrorReceivedEventArgs
{
    static const int FIELD__error = 1;


    //--//

};

struct Library_Lib_GHI_Utilities_InternalEvent
{
    static const int FIELD_STATIC__dispatcher = 25;
    static const int FIELD_STATIC__ControllerAreaNetworkActivity = 26;
    static const int FIELD_STATIC__RuntimeLoadableProceduresEvent = 27;
    static const int FIELD_STATIC__UsbDeviceConnected = 28;
    static const int FIELD_STATIC__UsbDeviceConnectionFailed = 29;
    static const int FIELD_STATIC__UsbDeviceDisconnected = 30;


    //--//

};

struct Library_Lib_GHI_Processor_InFieldUpdate
{
    static const int FIELD_STATIC__initialized = 31;
    static const int FIELD_STATIC__initializedType = 32;

    TINYCLR_NATIVE_DECLARE(NativeInitialize___STATIC__BOOLEAN__GHIProcessorInFieldUpdateTypes);
    TINYCLR_NATIVE_DECLARE(NativeLoad___STATIC__BOOLEAN__GHIProcessorInFieldUpdateTypes__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(NativeFlashAndReset___STATIC__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeAbort___STATIC__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeCalculateCRC16___STATIC__U2__GHIProcessorInFieldUpdateTypes);

    //--//

};

struct Library_Lib_GHI_IO_Audio
{
    TINYCLR_NATIVE_DECLARE(NativePlayPCM___STATIC__VOID__U1__SZARRAY_U1__I4__I4__I4);

    //--//

};

struct Library_Lib_GHI_IO_SignalCapture
{
    static const int FIELD__timeout = 1;
    static const int FIELD__disposed = 2;
    static const int FIELD__port = 3;

    TINYCLR_NATIVE_DECLARE(NativeRead___STATIC__I4__U4__BYREF_BOOLEAN__SZARRAY_U4__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(NativeRead___STATIC__I4__U4__BOOLEAN__SZARRAY_U4__I4__I4__I4);

    //--//

};

struct Library_Lib_GHI_IO_SignalGenerator
{
    static const int FIELD__pin = 1;
    static const int FIELD__disposed = 2;
    static const int FIELD__nativePointer = 3;

    TINYCLR_NATIVE_DECLARE(NativeConstructor___BOOLEAN__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeDispose___VOID);
    TINYCLR_NATIVE_DECLARE(NativeIsActive___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeSet___VOID__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeSet___BOOLEAN__BOOLEAN__SZARRAY_U4__I4__I4__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeSet___VOID__BOOLEAN__SZARRAY_U4__I4__I4__U4__BOOLEAN__U4);

    //--//

};

struct Library_Lib_GHI_IO_SoftwareI2CBus
{
    static const int FIELD__emptyBuffer = 1;
    static const int FIELD__disposed = 2;
    static const int FIELD__clockPin = 3;
    static const int FIELD__dataPin = 4;

    TINYCLR_NATIVE_DECLARE(NativeWriteRead___STATIC__BOOLEAN__I4__I4__U1__SZARRAY_U1__I4__I4__SZARRAY_U1__I4__I4__BYREF_I4__BYREF_I4);

    //--//

};

struct Library_Lib_GHI_IO_Storage_ExtendedWeakReferences
{
    TINYCLR_NATIVE_DECLARE(Flush___STATIC__VOID);

    //--//

};

struct Library_Lib_GHI_IO_Storage_Removable
{
    static const int FIELD__disposed = 1;


    //--//

};

struct Library_Lib_GHI_IO_Storage_SD
{
    static const int FIELD__id = 2;

    TINYCLR_NATIVE_DECLARE(NativeConstructor___VOID__U4);
    TINYCLR_NATIVE_DECLARE(NativeFinalize___VOID);
    TINYCLR_NATIVE_DECLARE(NativeMount___VOID__I4);
    TINYCLR_NATIVE_DECLARE(NativeUnmount___VOID);
    TINYCLR_NATIVE_DECLARE(IsSDCardPresent___STATIC__BOOLEAN);

    //--//

};

struct Library_Lib_GHI_IO_Storage_UsbMassStorage
{
    static const int FIELD__id = 2;

    TINYCLR_NATIVE_DECLARE(NativeConstructor___VOID__U4__U1__U1);
    TINYCLR_NATIVE_DECLARE(NativeFinalize___VOID);
    TINYCLR_NATIVE_DECLARE(NativeMount___VOID);
    TINYCLR_NATIVE_DECLARE(NativeUnmount___VOID);

    //--//

};

struct Library_Lib_GHI_Processor_AddressSpace
{
    TINYCLR_NATIVE_DECLARE(NativeWrite___STATIC__VOID__U4__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(NativeRead___STATIC__VOID__U4__SZARRAY_U1__I4__I4);

    //--//

};

struct Library_Lib_GHI_Processor_ApplicationProtection
{
    TINYCLR_NATIVE_DECLARE(NativeSetApplicationProtection___STATIC__VOID__U1__SZARRAY_U1);

    //--//

};

struct Library_Lib_GHI_Processor_Power
{
    static const int FIELD_STATIC__ethernetEnabled = 33;

    TINYCLR_NATIVE_DECLARE(NativeHibernate___STATIC__VOID__U4);
    TINYCLR_NATIVE_DECLARE(NativeSetEthernetOscillator___STATIC__VOID__BOOLEAN);

    //--//

};

struct Library_Lib_GHI_Processor_RealTimeClock
{
    static const int FIELD_STATIC__alarm = 34;

    TINYCLR_NATIVE_DECLARE(NativeSetTime___STATIC__VOID__I4__I4__I4__I4__I4__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(NativeGetTime___STATIC__VOID__BYREF_I4__BYREF_I4__BYREF_I4__BYREF_I4__BYREF_I4__BYREF_I4__BYREF_I4);
    TINYCLR_NATIVE_DECLARE(NativeSetAlarm___STATIC__VOID__I4__I4__I4__I4__I4__I4__I4__I4);

    //--//

};

struct Library_Lib_GHI_Processor_Register
{
    static const int FIELD__address = 1;

    TINYCLR_NATIVE_DECLARE(NativeWrite___VOID__U4);
    TINYCLR_NATIVE_DECLARE(NativeRead___U4);
    TINYCLR_NATIVE_DECLARE(NativeSetBits___VOID__U4);
    TINYCLR_NATIVE_DECLARE(NativeClearBits___VOID__U4);
    TINYCLR_NATIVE_DECLARE(NativeToggleBits___VOID__U4);
    TINYCLR_NATIVE_DECLARE(NativeIsValid___STATIC__BOOLEAN__U4);

    //--//

};

struct Library_Lib_GHI_Processor_RuntimeLoadableProcedures
{
    static const int FIELD_STATIC__imageAddress = 35;
    static const int FIELD_STATIC__imageSize = 36;
    static const int FIELD_STATIC__regionCount = 37;
    static const int FIELD_STATIC__imageData = 38;
    static const int FIELD_STATIC__NativeEvent = 39;

    TINYCLR_NATIVE_DECLARE(NativeInitializeZeroRegion___STATIC__VOID__U4__U4);
    TINYCLR_NATIVE_DECLARE(NativeLoadELF___STATIC__VOID__SZARRAY_U1__BYREF_U4__BYREF_U4__BYREF_U4);
    TINYCLR_NATIVE_DECLARE(NativeFindSymbolAddress___STATIC__U4__SZARRAY_U1__STRING__GHIProcessorRuntimeLoadableProceduresSymbolType);

    //--//

};

struct Library_Lib_GHI_Processor_Watchdog
{
    static const int FIELD_STATIC__lastResetCause = 40;
    static const int FIELD_STATIC__maxTimeout = 41;
    static const int FIELD_STATIC__timeout = 42;
    static const int FIELD_STATIC__timeoutSet = 43;
    static const int FIELD_STATIC__enabled = 44;

    TINYCLR_NATIVE_DECLARE(NativeLastResetCause___STATIC__U1);
    TINYCLR_NATIVE_DECLARE(NativeGetMaxTimeout___STATIC__U4);
    TINYCLR_NATIVE_DECLARE(NativeEnable___STATIC__VOID__U4);
    TINYCLR_NATIVE_DECLARE(NativeDisable___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(NativeResetCounter___STATIC__VOID);

    //--//

};

struct Library_Lib_GHI_Usb_Descriptors_BaseDescriptor
{
    static const int FIELD__Length = 1;
    static const int FIELD__Type = 2;


    //--//

};

struct Library_Lib_GHI_Usb_Descriptors_Auxiliary
{
    static const int FIELD__Payload = 3;


    //--//

};

struct Library_Lib_GHI_Usb_Descriptors_Configuration
{
    static const int FIELD__TotalLength = 3;
    static const int FIELD__NumberOfInterfaces = 4;
    static const int FIELD__Value = 5;
    static const int FIELD__Index = 6;
    static const int FIELD__Attributes = 7;
    static const int FIELD__MaxPower = 8;
    static const int FIELD__AuxiliaryDescriptors = 9;
    static const int FIELD__Interfaces = 10;


    //--//

};

struct Library_Lib_GHI_Usb_Descriptors_Device
{
    static const int FIELD__USBSpecificationNumber = 3;
    static const int FIELD__ClassCode = 4;
    static const int FIELD__SubclassCode = 5;
    static const int FIELD__ProtocalCode = 6;
    static const int FIELD__MaximumPacketSize = 7;
    static const int FIELD__VendorId = 8;
    static const int FIELD__ProductId = 9;
    static const int FIELD__ReleaseNumber = 10;
    static const int FIELD__ManufacturerIndex = 11;
    static const int FIELD__ProductIndex = 12;
    static const int FIELD__SerialNumberIndex = 13;
    static const int FIELD__NumberOfConfigurations = 14;


    //--//

};

struct Library_Lib_GHI_Usb_Descriptors_Endpoint
{
    static const int FIELD__Address = 3;
    static const int FIELD__Attributes = 4;
    static const int FIELD__MaximumPacketSize = 5;
    static const int FIELD__Interval = 6;
    static const int FIELD__AuxiliaryDescriptors = 7;


    //--//

};

struct Library_Lib_GHI_Usb_Descriptors_Interface
{
    static const int FIELD__Number = 3;
    static const int FIELD__AlternateSetting = 4;
    static const int FIELD__NumberEndpoints = 5;
    static const int FIELD__ClassCode = 6;
    static const int FIELD__SubclassCode = 7;
    static const int FIELD__ProtocolCode = 8;
    static const int FIELD__Index = 9;
    static const int FIELD__AuxiliaryDescriptors = 10;
    static const int FIELD__Endpoints = 11;


    //--//

};

struct Library_Lib_GHI_Usb_Position
{
    static const int FIELD__X = 1;
    static const int FIELD__Y = 2;
    static const int FIELD__Z = 3;


    //--//

};

struct Library_Lib_GHI_Utilities_Arrays
{
    TINYCLR_NATIVE_DECLARE(NativeInsertString___STATIC__VOID__SZARRAY_U1__I4__STRING__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeInsertFloat___STATIC__VOID__SZARRAY_U1__I4__R4);
    TINYCLR_NATIVE_DECLARE(NativeInsertInt32___STATIC__VOID__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(NativeExtractFloat___STATIC__R4__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(NativeExtractInt32___STATIC__I4__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(NativeSplitToArray___STATIC__I4__SZARRAY_U1__I4__CHAR__SZARRAY_R4);

    //--//

};

struct Library_Lib_GHI_Utilities_Crc
{
    TINYCLR_NATIVE_DECLARE(NativeCrc16___STATIC__U2__SZARRAY_U1__I4__I4__U2);
    TINYCLR_NATIVE_DECLARE(NativeCrc32___STATIC__U4__SZARRAY_U1__I4__I4__U4);

    //--//

};

struct Library_Lib_GHI_Utilities_Xtea
{
    static const int FIELD__key = 1;

    TINYCLR_NATIVE_DECLARE(NativeEncrypt___VOID__SZARRAY_U1__I4__I4__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(NativeDecrypt___VOID__SZARRAY_U1__I4__I4__SZARRAY_U1__I4);

    //--//

};

struct Library_Lib_GHI_IO_SoftwareI2CBus__I2CDevice
{
    static const int FIELD__bus = 1;
    static const int FIELD__address = 2;


    //--//

};

struct Library_Lib_GHI_Utilities_InternalEvent__InternalEventEventArgs
{
    static const int FIELD__eventId = 1;
    static const int FIELD__data = 2;


    //--//

};

struct Library_Lib_GHI_IO_ControllerAreaNetwork__Message
{
    static const int FIELD__data = 1;
    static const int FIELD__arbitrationId = 2;
    static const int FIELD__length = 3;
    static const int FIELD__isRTR = 4;
    static const int FIELD__isEID = 5;
    static const int FIELD__timeStamp = 6;


    //--//

};

struct Library_Lib_GHI_IO_ControllerAreaNetwork__MessageAvailableEventArgs
{
    static const int FIELD__available = 1;


    //--//

};

struct Library_Lib_GHI_Processor_RuntimeLoadableProcedures__NativeEventEventArgs
{
    static const int FIELD__data = 1;


    //--//

};

struct Library_Lib_GHI_Processor_RuntimeLoadableProcedures__NativeFunction
{
    static const int FIELD__address = 1;
    static const int FIELD__arguments = 2;
    static const int FIELD__argumentSizes = 3;
    static const int FIELD__emptyArray = 4;

    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4);
    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U4__I4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_I4__I4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_R4__I4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_I2__I4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U2__I4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_CHAR__I4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__I4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(InvokeNative___STATIC__I4__U4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1__SZARRAY_I1__I4__SZARRAY_U4);

    //--//

};

struct Library_Lib_GHI_Processor_Configuration__StartupLogo
{
    static const int FIELD_STATIC__width = 45;
    static const int FIELD_STATIC__height = 46;
    static const int FIELD_STATIC__x = 47;
    static const int FIELD_STATIC__y = 48;
    static const int FIELD_STATIC__enabled = 49;
    static const int FIELD_STATIC__image = 50;

    TINYCLR_NATIVE_DECLARE(NativeSupportedWidth___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(NativeSupportedHeight___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(NativeGetEnabled___STATIC__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeGetBitmap___STATIC__VOID__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(NativeGetCoords___STATIC__VOID__BYREF_I4__BYREF_I4);
    TINYCLR_NATIVE_DECLARE(NativeSave___STATIC__BOOLEAN__SZARRAY_U1__I4__I4__BOOLEAN);

    //--//

};

struct Library_Lib_GHI_IO_ControllerAreaNetwork__Timings
{
    static const int FIELD__propagation = 1;
    static const int FIELD__phase1 = 2;
    static const int FIELD__phase2 = 3;
    static const int FIELD__brp = 4;
    static const int FIELD__synchronizationJumpWidth = 5;
    static const int FIELD__useMultiBitSampling = 6;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_GHI_Hardware;

#endif  //_LIB_H_
