//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Lib.h"
#include "Lib_GHI_Hardware_Configuration__Display.h"

using namespace GHI::Hardware;


HRESULT Library_Lib_GHI_Hardware_Configuration__Display::NativeGetBootupMessage___STATIC__BOOLEAN( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        INT8 retVal = Configuration_Display::NativeGetBootupMessage( hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_INT8( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_Lib_GHI_Hardware_Configuration__Display::NativeSetBootupMessage___STATIC__BOOLEAN__BOOLEAN( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        INT8 param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8( stack, 0, param0 ) );

        INT8 retVal = Configuration_Display::NativeSetBootupMessage( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_INT8( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_Lib_GHI_Hardware_Configuration__Display::NativeGetRotation___STATIC__GHIHardwareConfigurationDisplayRotation( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        UINT8 retVal = Configuration_Display::NativeGetRotation( hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_UINT8( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_Lib_GHI_Hardware_Configuration__Display::NativeSetRotation___STATIC__BOOLEAN__GHIHardwareConfigurationDisplayRotation( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        UINT8 param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 0, param0 ) );

        INT8 retVal = Configuration_Display::NativeSetRotation( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_INT8( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_Lib_GHI_Hardware_Configuration__Display::NativeGetConfiguration___STATIC__VOID__BYREF_U4__BYREF_U4__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U4( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        UINT32 * param0;
        UINT8 heapblock0[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT32_ByRef( stack, heapblock0, 0, param0 ) );

        UINT32 * param1;
        UINT8 heapblock1[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT32_ByRef( stack, heapblock1, 1, param1 ) );

        INT8 * param2;
        UINT8 heapblock2[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8_ByRef( stack, heapblock2, 2, param2 ) );

        INT8 * param3;
        UINT8 heapblock3[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8_ByRef( stack, heapblock3, 3, param3 ) );

        INT8 * param4;
        UINT8 heapblock4[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8_ByRef( stack, heapblock4, 4, param4 ) );

        INT8 * param5;
        UINT8 heapblock5[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8_ByRef( stack, heapblock5, 5, param5 ) );

        INT8 * param6;
        UINT8 heapblock6[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8_ByRef( stack, heapblock6, 6, param6 ) );

        UINT8 * param7;
        UINT8 heapblock7[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ByRef( stack, heapblock7, 7, param7 ) );

        UINT8 * param8;
        UINT8 heapblock8[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ByRef( stack, heapblock8, 8, param8 ) );

        UINT8 * param9;
        UINT8 heapblock9[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ByRef( stack, heapblock9, 9, param9 ) );

        UINT8 * param10;
        UINT8 heapblock10[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ByRef( stack, heapblock10, 10, param10 ) );

        UINT8 * param11;
        UINT8 heapblock11[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ByRef( stack, heapblock11, 11, param11 ) );

        UINT8 * param12;
        UINT8 heapblock12[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ByRef( stack, heapblock12, 12, param12 ) );

        UINT32 * param13;
        UINT8 heapblock13[CLR_RT_HEAP_BLOCK_SIZE];
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT32_ByRef( stack, heapblock13, 13, param13 ) );

        Configuration_Display::NativeGetConfiguration( param0, param1, param2, param3, param4, param5, param6, param7, param8, param9, param10, param11, param12, param13, hr );
        TINYCLR_CHECK_HRESULT( hr );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock0, 0 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock1, 1 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock2, 2 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock3, 3 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock4, 4 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock5, 5 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock6, 6 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock7, 7 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock8, 8 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock9, 9 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock10, 10 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock11, 11 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock12, 12 ) );
        TINYCLR_CHECK_HRESULT( Interop_Marshal_StoreRef( stack, heapblock13, 13 ) );
    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_Lib_GHI_Hardware_Configuration__Display::NativeSetConfiguration___STATIC__BOOLEAN__U4__U4__BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN__U1__U1__U1__U1__U1__U1__U4( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        UINT32 param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT32( stack, 0, param0 ) );

        UINT32 param1;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT32( stack, 1, param1 ) );

        INT8 param2;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8( stack, 2, param2 ) );

        INT8 param3;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8( stack, 3, param3 ) );

        INT8 param4;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8( stack, 4, param4 ) );

        INT8 param5;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8( stack, 5, param5 ) );

        INT8 param6;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8( stack, 6, param6 ) );

        UINT8 param7;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 7, param7 ) );

        UINT8 param8;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 8, param8 ) );

        UINT8 param9;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 9, param9 ) );

        UINT8 param10;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 10, param10 ) );

        UINT8 param11;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 11, param11 ) );

        UINT8 param12;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 12, param12 ) );

        UINT32 param13;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT32( stack, 13, param13 ) );

        INT8 retVal = Configuration_Display::NativeSetConfiguration( param0, param1, param2, param3, param4, param5, param6, param7, param8, param9, param10, param11, param12, param13, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_INT8( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}
